### ISSUE TITLE
Release 1.2.1 breaks build with Swift 4.1

### ISSUE THREAD

**Issue by PetrPrazak** [nixzhu/Proposer#13]
Last version cannot be compiled with Swift 4.1 (Xcode 9.4.1).
```
Proposer.swift:38:69: error: binary operator '==' cannot be applied to operands of type '() -> AVAudioSessionRecordPermission' and '_'
            return AVAudioSession.sharedInstance().recordPermission == .undetermined
```
Maybe it would warrant a major version change?

**Comment by nixzhu** [comment]
The best way is convert your project to Swift 4.2. Otherwise specify the pod version to 1.2.0.
